apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  revisionHistoryLimit: 0
  replicas: 4
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      serviceAccountName: backend
      initContainers:
        - name: wait-for-redis
          image: ghcr.io/sikalabs/slu:v0.95.1
          command:
            - "/bin/sh"
            - "-c"
            - "slu wait-for tcp -a redis:6379"
        - name: wait-for-migrations
          image: sikalabs/kubectl
          command:
            - "/bin/sh"
            - "-c"
            - "sleep 2 && kubectl wait --for=condition=complete --timeout=600s job/backend-migrations"
      containers:
        - name: main
          image: ghcr.io/ondrejsika/counter
          ports:
            - containerPort: 8000
          env:
            - name: REDIS
              value: redis
            - name: SLOW_START
              value: '5'
            - name: EXTRA_TEXT
              value: v5
          startupProbe:
            httpGet:
              path: /readyz
              port: 8000
          livenessProbe:
            httpGet:
              path: /livez
              port: 8000
          resources:
            requests:
              cpu: 40m
              memory: 20Mi
            limits:
              cpu: 200m
              memory: 100Mi
