apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: backend
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    resourceNames: ["backend-migrations"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: backend
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: backend
subjects:
  - kind: ServiceAccount
    name: backend
